name: Build Open Meteo binding

on:
  workflow_dispatch:
  push:

jobs:
  build:
    env:
      addon-path: 'openhab-addons/bundles/com.obones.binding.openmeteo'
      is-release: startsWith(${{ github.ref }}, '/refs/tags/v')
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]
        maven: [ '3.9.4' ]
        os: [ 'ubuntu-22.04' ]
        addons-ref: [ '4.1.x', '4.2.x', '4.3.x' ]
        include:
          - java: 21
            addons-ref: 5.0.x
            os: ubuntu-22.04
            maven: 3.9.4
          - java: 21
            addons-ref: main
            os: ubuntu-22.04
            maven: 3.9.4
    name: Build on ${{ matrix.addons-ref }} (Java ${{ matrix.java }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      attestations: write
    steps:
      - name: Checkout openhab-addons
        uses: actions/checkout@v4
        with:
          repository: openhab/openhab-addons
          path: openhab-addons
          ref: ${{ matrix.addons-ref }}

      - name: Checkout addon in ${{ env.addon-path }}
        uses: actions/checkout@v4
        with:
          path: ${{ env.addon-path }}

      - name: Apply patches for version ${{ matrix.addons-ref }} from ${{ format('"{0}/patches/{1}.patch"', env.addon-path, matrix.addons-ref) }}
        if: ${{ hashFiles(format('{0}/patches/{1}.patch', env.addon-path, matrix.addons-ref)) != '' }}
        working-directory: ${{ env.addon-path }}
        run: git apply patches/${{ matrix.addons-ref }}.patch

      - name: Set up Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/openhab
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Set up Maven ${{ matrix.maven }}
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: ${{ matrix.maven }}

      - name: Build with maven
        working-directory: ${{ env.addon-path }}
        run: mvn clean install -DskipChecks

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ env.is-release }}
        with:
          name: com.obones.binding.openmeteo-openhab_${{ matrix.addons-ref }}-java_${{ matrix.java }}
          path: |
            ${{ env.addon-path }}/target/com.obones.binding.openmeteo*.jar
            !${{ env.addon-path }}/target/com.obones.binding.openmeteo*-sources.jar

      - name: Create attestation
        uses: actions/attest-build-provenance@v1
        if: ${{ env.is-release }}
        with:
          subject-path: |
            ${{ env.addon-path }}/target/com.obones.binding.openmeteo*.jar
            !${{ env.addon-path }}/target/com.obones.binding.openmeteo*-sources.jar

